name: mapir_gl
description: A Flutter plugin for integrating Map.ir Maps SDK inside a Flutter widget in iOS and Android applications.
version: 0.0.8-beta1
#author: Mapir <map.shiveh@gmail.com>
homepage: https://github.com/tobrun/flutter-mapbox-gl

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.mapboxgl
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
